okhv = "OKH-LOSHv1.0"
name = "MAXWELL MK2 Mover"
repo = "https://github.com/refaqt/stoq/tree/main/modules/maxwell/modules/mk2-mover"
version = "0.1.0"
license = "CC-BY-SA-4.0"
licensor = "REFAQT"
function = "Iron core linear motor mover, 86 mm wide, in four coil lengths."

[brand]
name = "Maxwell (Dongguan) Intelligent Equipment Co., Ltd."
website = "https://www.maxwelldg.com"
cad-terms = "https://www.maxwelldg.com"
redistribute = true
